### ISSUE TITLE
Compatibility with puma and Rails - "WARNING: Detected 2 Thread(s) started in app boot:"

### ISSUE THREAD

**Issue by ndbroadbent** [ruby-concurrency/concurrent-ruby#868]
```
* Operating system:                mac + linux
* Ruby implementation:             Ruby
* `concurrent-ruby` version:       1.1.6
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used: no
```

Hello, I'm trying to debug a thread warning in puma. Here's the issue I opened over there: https://github.com/puma/puma/issues/2237

The problem seems to be that requiring [`lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb`](https://github.com/ruby-concurrency/concurrent-ruby/blob/f749b81cb6c6291640c0004b57e60dbc2b59a72b/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb#L38-L60) immediately starts a new `Thread`.

Here's the stack trace when puma loads my application:

```
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:8:in `<module:Concurrent>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:4:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/thread_local_var.rb:2:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/thread_local_var.rb:2:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:5:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:5:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomics.rb:8:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomics.rb:8:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent.rb:6:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent.rb:6:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger_silence.rb:5:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger_silence.rb:5:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:3:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:3:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support.rb:29:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support.rb:29:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails.rb:7:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails.rb:7:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/all.rb:3:in `require'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/all.rb:3:in `<top (required)>'
/Users/myuser/code/myapp/config/application.rb:7:in `require'
/Users/myuser/code/myapp/config/application.rb:7:in `<top (required)>'
/Users/myuser/code/myapp/config/environment.rb:4:in `require_relative'
/Users/myuser/code/myapp/config/environment.rb:4:in `<top (required)>'
config.ru:5:in `require_relative'
config.ru:5:in `block in <main>'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/cluster.rb:413:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
/Users/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.6.5/bin/puma:23:in `load'
/Users/myuser/.rbenv/versions/2.6.5/bin/puma:23:in `<main>'
```

When puma is running in "clustered" mode, it forks a new process for each worker, so the Thread started by the `RubyThreadLocalVar` class is not running inside any of these worker processes. Is this a problem? My first impression is that this might cause a memory leak because none of the thread-local variables are ever getting released and garbage collected in my puma workers. (But I'm not sure which parts of Rails are using this.)

New threads can be started inside `puma.on_worker_boot`, so should we doing something like:

```
puma.on_worker_boot do
  Concurrent::RubyThreadLocalVar.start_thread!
end
```

Or maybe puma should do this automatically if it detects the concurrent-ruby library?

Thanks for your time!

**Comment by nateberkopec** [comment]
Should concurrent-ruby be creating threads at require-time? I think this could create risks for anyone using a forking webserver.

**Comment by timriley** [comment]
I just noticed this error in my app running via Puma, too.

I took a look at the latest code in `lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb ` and it seems like the issue might have been fixed by the changes in https://github.com/ruby-concurrency/concurrent-ruby/pull/856?

This PR was merged only yesterday! Lucky timing :)

@pitr-ch out of interest, were you aware of this issue when working on the changes in that PR?

**Comment by pitr-ch** [comment]
I was not, indeed a lucky timing :)
Could you test the fix from #856 in your environment?

**Comment by MTres19** [comment]
I had a very similar if not the same issue and the patch from that pull request does does eliminate the warning for concurrent-ruby. I still get the warning for ActiveRecord, but I guess that is a separate issue. Thank you all for your work!

**Comment by nateberkopec** [comment]
Released, so I think this can be closed.

**Comment by pitr-ch** [comment]
@nateberkopec please, could you confirm the warning is gone? Then I'll close.

**Comment by dentarg** [comment]
@pitr-ch I can confirm that I no longer see the warning using concurrent-ruby 1.1.7 (I was using concurrent-ruby 1.1.6 before). My app uses Puma 4.3.5 and Ruby 2.5.

**Comment by pitr-ch** [comment]
@dentarg Thank you 👍 for confirming!

**Comment by h0jeZvgoxFepBQ2C** [comment]
I'm still seeing this with Ruby 2.6.6 and Rails 5.2.4.3:

```
● puma_app-admin.service - Puma HTTP Server
   Loaded: loaded (/etc/systemd/system/puma_app-admin.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-09-08 21:26:14 CEST; 23min ago
  Process: 31911 ExecReload=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors
pumactl -F /home/user/apps/app-admin/shared/puma.rb restart (code=exited, status=0/SUCCESS)
 Main PID: 25736 (ruby)
    Tasks: 26
   Memory: 399.2M
      CPU: 2min 2.902s
   CGroup: /system.slice/puma_app-admin.service
           ├─25736 puma 4.3.5 (unix:///home/user/apps/app-admin/shared/sockets/puma.app-admin
.sock?backlog=8000) [20200908194103]
           ├─32431 puma: cluster worker 0: 25736 [20200908194103]

           └─32443 puma: cluster worker 1: 25736 [20200908194103]


Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Environment: production
Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Process workers: 2
Sep 08 21:26:15 appake20 rbenv[25736]: [25736] * Preloading application
Sep 08 21:26:22 appake20 rbenv[25736]: [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagic
k" instead
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] * Activated unix:///home/user/apps/app-admin/s
hared/sockets/puma.app-admin.sock?backlog=8000
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] ! WARNING: Detected 1 Thread(s) started in app boot:
Sep 08 21:26:49 appake20 rbenv[25736]: [25736] ! #<Thread:0x000000000a6b71c8@/home/user/apps/fl
ave-admin/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/ab
stract/connection_pool.rb:299 sleep> - /home/user/apps/app-admin/shared/bundle/ruby/2.6.0/gems/
activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep'

```

Even though I have concurrent-ruby 1.1.7 in my Gemfile.lock?
